server.port=8082

spring.datasource.url=jdbc:h2:mem:ms_empresa
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

jwt.secret=VKF.x8zKYvfnK%G(F[B/
jwt.expiration=600000

ms.usuario.url=http://localhost:8081
ms.catalogo.url=http://localhost:8083
ms.venda.url=http://localhost:8084
ms.veiculo.url=http://localhost:8085
